---
title: "Assignment 3"
author: "Christina Lin"
date: "10/29/2021"
output:
  github_document: default
  html_document:
    html_preview: false
  word_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "http://cran.rstudio.com"))
library(tidyverse)
library(tidytext)
library(xml2)
```

# Part 1: APIs


```{r}
# Downloading the website
website <- xml2::read_html("https://pubmed.ncbi.nlm.nih.gov/?term=sars-cov-2+trial+vaccine")

# Finding the number of papers
counts <- xml2::xml_find_first(website, xpath = "/html/body/main/div[9]/div[2]/div[2]/div[1]/div[1]/span")

counts <- as.character(counts)
counts <- stringr::str_extract(counts, "[[:digit:],]+")
counts <- stringr::str_remove_all(counts, ",")
counts <- as.integer(counts)
```

When searched on the PubMed website with the term "sars-cov-2 trial vaccine", there are `r counts` results.


## Using the NCBI API

```{r}
library(httr)
query_ids <- GET(
  url   = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi",
  query = list(
    db = "pubmed",
    term = "sars-cov-2 trial vaccine",
    retmax = "5000"
)
)
# Extracting the content of the response of GET
ids <- httr::content(query_ids)

# Turn the result into a character vector
ids <- as.character(ids)

# Find all the ids 
ids <- stringr::str_extract_all(ids, "<Id>[[:digit:]]+</Id>")[[1]]
# Remove all the leading and trailing <Id> </Id>. Make use of "|"
ids <- stringr::str_remove_all(ids, "<Id>|</Id>")

```

Searching the NCBI API returns `r length(ids)` UIDs for publications associated with "sars-cov-2 trial vaccine". 


Now getting the details for the first 250 papers. 
```{r}
# Getting the abstract of the papers


publications <- GET(
  url   = "https://eutils.ncbi.nlm.nih.gov/",
  path = "entrez/eutils/efetch.fcgi",
  query = list(
    db = "pubmed",
    id = I(paste(ids, collapse=",")),
    retmax = "250",
    rettype = "abstract"
    )
)

# Turning the output into character vector
publication <- httr::content(publications)
publications_txt <- as.character(publication)

```


# Part 2: Text Mining

